### ISSUE TITLE
Assume / Assert is slow

### ISSUE THREAD

**Issue by AntonXue** [AntonXue/G2#13]
There is an approximately factor of 2 speed reduction when we condition with `Assume` instead of `App`. I have no idea why this happens because profiling with cabal based packages is a living nightmare.

Some interesting things to point out:
* The test ran on my machine was 147 seconds vs 76 seconds, which is approximately a factor of 2 difference.
* `App (Lam b ...) exp` bindings from `App` in `initStateCond` would theoretically immediately add `(b, exp)` into the environment. This is potentially bad if the binder is referred to multiple times within the `Lam` body because we cannot abuse graph reduction at the Core Haskell level.
* The fact that there is a factor of 2 difference seems to suggest that the `exp` in the beginning is evaluated twice, redundantly.

Some possibilities include:
* GHC compiles `stepAssume` / `stepAssert` in a way that somehow violates the appearance of graph reduction properties we were trying to make it do. If this were true, it would be truly ironic.
* ???

**Comment by BillHallahan** [comment]
Complete overhaul of evaluator, this is fixed...
